project_id = "bdrfnvdhygasmxxvxvtt"

[functions.create-user]
verify_jwt = true

[functions.notify-whatsapp-reservation]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = true

